// ╔═══════════════════════════════════════════════════════════════════════╗
// ║  ERZEUGT — nicht von Hand aendern.                                    ║
// ║  Quelle: multicam-planner src/data/rigs.ts                           ║
// ║  Nachziehen: npm run katalog:uebernahme                               ║
// ║  Pruefen:    npm run katalog:check                                    ║
// ╚═══════════════════════════════════════════════════════════════════════╝
//
// BELEGLAGE: kein Datenblatt-Link je Eintrag (B-11).
//
// 49 Eintraege, kein einziger mit Beleg. Die Quelle nennt keine
// Hersteller-Adresse; eine zu erfinden waere schlimmer als die Luecke.
//
// JEDER EINTRAG TRAEGT `portsUnknown: true`. Die Quelle kennt keine
// Anschluesse, und eine erfundene Belegung saehe im Plan genauso autoritativ
// aus wie eine echte — sie wanderte still in BOM, Patchliste und Verkabelung.
// Der Marker ist der Weg aus `docs/device-identity-concept.md`: der
// Plan-Check fordert die Datenblatt-Ergaenzung ein, und sobald jemand reale
// Ports eintraegt, entfernt die Eigenschaften-Leiste das Flag selbst.
//
// ─── OHNE DATENBLATT-LINK, UND DAS STEHT HIER ──────────────────────────────
//
// Die Quelle fuehrt fuer keines dieser Rigs eine Hersteller-Adresse. Eine zu
// erfinden waere schlimmer als keine; `catalogueEvidence` zaehlt sie deshalb
// vollstaendig als unbelegt, und `catalogSourceUrls.test.ts` fuehrt diese
// Datei in der Liste der Kataloge ohne Beleg.
//
// Die Maße dagegen SIND belegt — sie stehen im Kopf von `rigs.ts` mit ihrer
// Herkunft, einschliesslich der Stellen, an denen die Objektivhoehe geschaetzt
// ist. Diese Schaetzungen sind dort im `notes`-Feld markiert und kommen mit.
import type { EquipmentTemplate } from '../types/equipment'

const RIG = 'Tripods'

/** Katalog-Eintrag: stabile Geraetetyp-Id plus Vorlage. `match` traegt die
 *  normalisierten Namensformen, ueber die ein Import ohne GUID aufloest. */
export interface RigEntry {
  deviceTypeId: string
  match: string[]
  template: EquipmentTemplate
}

export const RIG_CATALOG: RigEntry[] = [
  {
    match: ['stativstandard'],
    deviceTypeId: 'f98df453-540c-5027-8ce8-f9f71a5f13b9',
    template: {
      name: 'Stativ (Standard)',
      category: RIG,
      subtitle: 'tripod',
      notes: '0.6-1.9 m · payload 25 kg · footprint 0.9x0.9 m',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['stativhochtall'],
    deviceTypeId: 'bd28325e-5e4e-5afd-bafa-f7fc10c5014e',
    template: {
      name: 'Stativ (hoch / Tall)',
      category: RIG,
      subtitle: 'tripod',
      notes: '1-2.6 m · payload 25 kg · footprint 1.1x1.1 m',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['babystativ'],
    deviceTypeId: 'a2eaeda8-9f64-5825-afdd-ffebe4c50bd1',
    template: {
      name: 'Baby-Stativ',
      category: RIG,
      subtitle: 'tripod',
      notes: '0.35-0.9 m · payload 25 kg · footprint 0.7x0.7 m',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['hihat'],
    deviceTypeId: '066a7d66-863e-5a78-8aac-bfac160dc385',
    template: {
      name: 'Hi-Hat',
      category: RIG,
      subtitle: 'hihat',
      notes: '0.12-0.3 m · payload 30 kg · footprint 0.5x0.5 m',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['vintenospreyelite'],
    deviceTypeId: '6a13db76-e534-519c-9af2-954a836a2f91',
    template: {
      name: 'Vinten Osprey Elite',
      category: RIG,
      subtitle: 'pedestal',
      notes: '0.62-1.62 m · payload 80 kg · footprint 1x1 m',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['sachtlercombipedestal'],
    deviceTypeId: '9f27017b-897d-5efa-b264-85ed2383b03c',
    template: {
      name: 'Sachtler Combi-Pedestal',
      category: RIG,
      subtitle: 'pedestal',
      notes: '0.6-1.55 m · payload 60 kg · footprint 1x1 m',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['wanddeckenhalter'],
    deviceTypeId: '8498cb05-887a-59c7-a478-614f5b0d6825',
    template: {
      name: 'Wand-/Deckenhalter',
      category: RIG,
      subtitle: 'fixed',
      notes: '0-12 m · payload 15 kg · footprint 0.2x0.2 m',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['jimmyjibtriangle6ft'],
    deviceTypeId: 'c1ac4913-1b83-5f3c-888f-9a72dc59c6d2',
    template: {
      name: 'Jimmy Jib Triangle 6 ft',
      category: RIG,
      subtitle: 'jib',
      notes: '0.3-3 m · arm 1.83 m · travel 1.4 m · payload 23 kg · footprint 3.66x7.32 m · Ausleger aus 3-ft-Sektionen. Objektivhöhe geschätzt (Drehpunkt 1.5 m, ~55°). Bis 30 ft ~23 kg Nutzlast.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['jimmyjibtriangle9ft'],
    deviceTypeId: 'fd5e7cb4-be7e-59f5-9cdd-b0854d4fc5b0',
    template: {
      name: 'Jimmy Jib Triangle 9 ft',
      category: RIG,
      subtitle: 'jib',
      notes: '0.3-3.7 m · arm 2.74 m · travel 2.2 m · payload 23 kg · footprint 3.66x7.32 m · Ausleger aus 3-ft-Sektionen. Objektivhöhe geschätzt (Drehpunkt 1.5 m, ~55°). Bis 30 ft ~23 kg Nutzlast.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['jimmyjibtriangle12ft'],
    deviceTypeId: 'bbfcb2e6-60d0-5d82-b10b-8ce6d3f7712a',
    template: {
      name: 'Jimmy Jib Triangle 12 ft',
      category: RIG,
      subtitle: 'jib',
      notes: '0.3-4.5 m · arm 3.66 m · travel 2.9 m · payload 23 kg · footprint 3.66x7.32 m · Ausleger aus 3-ft-Sektionen. Objektivhöhe geschätzt (Drehpunkt 1.5 m, ~55°). Bis 30 ft ~23 kg Nutzlast.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['jimmyjibtriangle15ft'],
    deviceTypeId: '7005472f-753d-5c94-9887-1792231a75de',
    template: {
      name: 'Jimmy Jib Triangle 15 ft',
      category: RIG,
      subtitle: 'jib',
      notes: '0.3-5.2 m · arm 4.57 m · travel 3.6 m · payload 23 kg · footprint 3.66x7.32 m · Ausleger aus 3-ft-Sektionen. Objektivhöhe geschätzt (Drehpunkt 1.5 m, ~55°). Bis 30 ft ~23 kg Nutzlast.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['jimmyjibtriangle18ft'],
    deviceTypeId: '8ef1b59b-972f-5885-8f75-3c25dcc1d702',
    template: {
      name: 'Jimmy Jib Triangle 18 ft',
      category: RIG,
      subtitle: 'jib',
      notes: '0.3-6 m · arm 5.49 m · travel 4.3 m · payload 23 kg · footprint 3.66x7.32 m · Ausleger aus 3-ft-Sektionen. Objektivhöhe geschätzt (Drehpunkt 1.5 m, ~55°). Bis 30 ft ~23 kg Nutzlast.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['jimmyjibtriangle24ft'],
    deviceTypeId: '5956aa01-35fc-5f0e-aef4-2a4d7c27900d',
    template: {
      name: 'Jimmy Jib Triangle 24 ft',
      category: RIG,
      subtitle: 'jib',
      notes: '0.3-7.5 m · arm 7.32 m · travel 5.7 m · payload 23 kg · footprint 7.32x7.32 m · Ausleger aus 3-ft-Sektionen. Objektivhöhe geschätzt (Drehpunkt 1.5 m, ~55°). Bis 30 ft ~23 kg Nutzlast.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['jimmyjibtriangle30ft'],
    deviceTypeId: 'ed63eb97-1cd2-53e2-8f48-6446f2eff75b',
    template: {
      name: 'Jimmy Jib Triangle 30 ft',
      category: RIG,
      subtitle: 'jib',
      notes: '0.3-9 m · arm 9.14 m · travel 7.2 m · payload 23 kg · footprint 7.32x7.32 m · Ausleger aus 3-ft-Sektionen. Objektivhöhe geschätzt (Drehpunkt 1.5 m, ~55°). Bis 30 ft ~23 kg Nutzlast.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['jimmyjibtriangle40ft'],
    deviceTypeId: '07e9e834-0f94-5748-a95c-6cb38cfb08e5',
    template: {
      name: 'Jimmy Jib Triangle 40 ft',
      category: RIG,
      subtitle: 'jib',
      notes: '0.3-11.5 m · arm 12.19 m · travel 9.6 m · payload 11 kg · footprint 7.32x7.32 m · Ausleger aus 3-ft-Sektionen. Objektivhöhe geschätzt (Drehpunkt 1.5 m, ~55°). Bei 40 ft nur leichte Kameras (~11 kg).',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['technocrane15'],
    deviceTypeId: 'a41e3cdf-555b-58cb-ba15-0796d4d2d38d',
    template: {
      name: 'Technocrane 15′',
      category: RIG,
      subtitle: 'technocrane',
      notes: '0.5-4.57 m · arm 4.95 m · telescope 2.49 m · travel 2.49 m · payload 36 kg · footprint 0.79x3 m · Basisbreite 2′7″, Türdurchfahrt ab 6′.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['technocrane22'],
    deviceTypeId: '94eee811-1bae-555f-864e-baf41139f005',
    template: {
      name: 'Technocrane 22′',
      category: RIG,
      subtitle: 'technocrane',
      notes: '0.5-7.32 m · arm 8.25 m · telescope 4.72 m · travel 4.72 m · payload 16 kg · footprint 0.79x3.5 m · Teleskopiert mit ~4′9″/s (1.45 m/s). Nutzlast 35 lb.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['supertechno15'],
    deviceTypeId: '4f82e032-40c8-563f-89cf-e801d1bb527a',
    template: {
      name: 'SuperTechno 15′',
      category: RIG,
      subtitle: 'technocrane',
      notes: '0.5-5.18 m · arm 5.87 m · telescope 2.87 m · travel 2.87 m · payload 36 kg · footprint 0.85x3.2 m · 15′ unterschlagen, 17′ überschlagen.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['supertechno30'],
    deviceTypeId: '2f9c8a22-5315-5865-af16-d140b755056e',
    template: {
      name: 'SuperTechno 30′',
      category: RIG,
      subtitle: 'technocrane',
      notes: '0.6-9.14 m · arm 11.94 m · telescope 6.91 m · travel 6.91 m · payload 36 kg · footprint 1.1x4.5 m',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['supertechno50'],
    deviceTypeId: 'b8e2fccd-ecac-5d1f-bc90-d6019ffee4f8',
    template: {
      name: 'SuperTechno 50′',
      category: RIG,
      subtitle: 'technocrane',
      notes: '0.8-15.24 m · arm 18.29 m · telescope 12.19 m · travel 12.19 m · payload 36 kg · footprint 1.3x6 m · Zwischengröße der Baureihe — Maße überschlägig.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['supertechno75'],
    deviceTypeId: '313d004d-7448-5278-a4a7-5b33e0ee1328',
    template: {
      name: 'SuperTechno 75′',
      category: RIG,
      subtitle: 'technocrane',
      notes: '1-24.38 m · arm 27.15 m · telescope 19.1 m · travel 19.1 m · payload 36 kg · footprint 1.6x8 m · 80′ überschlagene Objektivhöhe.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['scorpio45'],
    deviceTypeId: '27fe1fb9-86aa-55aa-8707-31bca666fd68',
    template: {
      name: 'Scorpio 45′',
      category: RIG,
      subtitle: 'technocrane',
      notes: '0.8-13.72 m · arm 15.85 m · telescope 9.14 m · travel 9.14 m · payload 36 kg · footprint 1.3x5.5 m · Maße überschlägig.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['jlfisherfishermodel10', 'fishermodel10'],
    deviceTypeId: '7f98d865-4ef7-5e2a-b73a-d876d030c2cf',
    template: {
      name: 'J.L. Fisher Fisher Model 10',
      category: RIG,
      subtitle: 'dolly',
      notes: '0.58-1.75 m · travel 4.88 m · payload 90 kg · footprint 0.78x1.35 m · Spurweite 24.5″ (0.62 m).',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['jlfisherfishermodel11', 'fishermodel11'],
    deviceTypeId: '9caef1b2-b639-50a8-8b3d-60bb27552ee5',
    template: {
      name: 'J.L. Fisher Fisher Model 11',
      category: RIG,
      subtitle: 'dolly',
      notes: '0.53-1.68 m · travel 4.88 m · payload 80 kg · footprint 0.74x1.25 m · Spurweite 24.5″ (0.62 m).',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['pantherclassic'],
    deviceTypeId: 'ce969d7c-234e-56d3-b834-154f4fc40662',
    template: {
      name: 'Panther Classic',
      category: RIG,
      subtitle: 'dolly',
      notes: '0.55-1.8 m · travel 4.88 m · payload 100 kg · footprint 0.8x1.2 m',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['doorwaydolly'],
    deviceTypeId: '2857af47-03be-5fa0-bd53-7d4cea55c1e2',
    template: {
      name: 'Doorway Dolly',
      category: RIG,
      subtitle: 'dolly',
      notes: '0.45-1.6 m · travel 3.66 m · payload 70 kg · footprint 0.71x1.22 m · Passt durch Standardtüren.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['westerndolly'],
    deviceTypeId: '33d9b9cf-46c0-53f5-9ee7-3b45388c66a3',
    template: {
      name: 'Western Dolly',
      category: RIG,
      subtitle: 'dolly',
      notes: '0.4-1.5 m · travel 3.66 m · payload 90 kg · footprint 0.91x1.52 m',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['skaterdollytischschiene'],
    deviceTypeId: 'd28def98-ef07-5649-9ade-f75625e35222',
    template: {
      name: 'Skater-Dolly (Tischschiene)',
      category: RIG,
      subtitle: 'dolly',
      notes: '0.15-0.45 m · travel 2.44 m · payload 8 kg · footprint 0.35x0.35 m · Kleines Schienensystem, gerade + 45°-Kurven.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['slider60cm'],
    deviceTypeId: 'b5476f4a-adc8-5491-a249-59052783df80',
    template: {
      name: 'Slider 60 cm',
      category: RIG,
      subtitle: 'slider',
      notes: '0.2-1.8 m · travel 0.6 m · payload 10 kg',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['slider100cm'],
    deviceTypeId: '178afad8-37c0-59f2-b7e9-69e5d670cd5e',
    template: {
      name: 'Slider 100 cm',
      category: RIG,
      subtitle: 'slider',
      notes: '0.2-1.8 m · travel 1 m · payload 12 kg',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['slider150cm'],
    deviceTypeId: '9b7ddccf-d6e2-544c-ae07-9db720daa946',
    template: {
      name: 'Slider 150 cm',
      category: RIG,
      subtitle: 'slider',
      notes: '0.2-1.8 m · travel 1.5 m · payload 15 kg',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['danadollyspeedrail'],
    deviceTypeId: '9fa2bcf3-209a-5a7f-aac0-67368c051c4c',
    template: {
      name: 'Dana Dolly (Speedrail)',
      category: RIG,
      subtitle: 'slider',
      notes: '0.3-1.8 m · travel 1.8 m · payload 20 kg · Länge über Speedrail-Rohre frei wählbar.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['spidercammini'],
    deviceTypeId: '732d5bd4-961a-5f0b-a726-7efc8b5eb992',
    template: {
      name: 'Spidercam Mini',
      category: RIG,
      subtitle: 'cablecam',
      notes: '2-15 m · travel 40 m · payload 12 kg · Kompakteste Variante.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['spidercamlight'],
    deviceTypeId: '52f4961a-d9d4-5aa4-a43b-f06f46b2cfd0',
    template: {
      name: 'Spidercam Light',
      category: RIG,
      subtitle: 'cablecam',
      notes: '2-25 m · travel 80 m · payload 15 kg · Für kleinere Räume/Hallen.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['spidercamfield'],
    deviceTypeId: '2d7538a9-6149-5f0a-8015-633fafd16b18',
    template: {
      name: 'Spidercam Field',
      category: RIG,
      subtitle: 'cablecam',
      notes: '3-40 m · travel 150 m · payload 20 kg · Grosse Stadien/Flächen, 4 Seile.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['drohnefpvleicht'],
    deviceTypeId: '9c41d2bb-501f-5ab6-801c-0820400292d4',
    template: {
      name: 'Drohne (FPV / leicht)',
      category: RIG,
      subtitle: 'drone',
      notes: '0.5-120 m · travel 200 m · payload 1.5 kg',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['drohneheavylift'],
    deviceTypeId: '44496013-7572-5141-b86a-f346a45f32cb',
    template: {
      name: 'Drohne (Heavy-Lift)',
      category: RIG,
      subtitle: 'drone',
      notes: '1-120 m · travel 150 m · payload 10 kg',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['scherenbhne8m'],
    deviceTypeId: 'f7a1dfc5-8d51-577d-ad27-e538e11584e8',
    template: {
      name: 'Scherenbühne 8 m',
      category: RIG,
      subtitle: 'scissorlift',
      notes: '1.2-8 m · payload 200 kg · footprint 1.2x2.5 m',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['scherenbhne12m'],
    deviceTypeId: '22e73c8f-5b9f-522c-8e64-c2c214e1f278',
    template: {
      name: 'Scherenbühne 12 m',
      category: RIG,
      subtitle: 'scissorlift',
      notes: '1.2-12 m · payload 250 kg · footprint 1.5x2.9 m',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['newtonnordicnewtons2remotehead', 'newtons2remotehead'],
    deviceTypeId: '427856b1-605c-52ce-840d-a6972dce883f',
    template: {
      name: 'Newton Nordic Newton S2 (Remote-Head)',
      category: RIG,
      subtitle: 'remotehead',
      notes: '0.3-3 m · payload 12 kg · Gyro-stabilisiert, Pan/Tilt/Roll + Zoom/Fokus/Blende.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['slidekamerabullheadstudioremotehead', 'bullheadstudioremotehead'],
    deviceTypeId: '6759e7c6-420f-5852-a99e-774e98770097',
    template: {
      name: 'Slidekamera Bullhead Studio (Remote-Head)',
      category: RIG,
      subtitle: 'remotehead',
      notes: '0.3-3 m · payload 10 kg · 2-Achs-Kopf für Kräne und Slider.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['fahrzeughoodmotorhaube'],
    deviceTypeId: '0be32671-f70a-50d8-8009-5c0f1f67e239',
    template: {
      name: 'Fahrzeug — Hood/Motorhaube',
      category: RIG,
      subtitle: 'carmount',
      notes: '1-1.6 m · travel 50 m · payload 20 kg',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['fahrzeughostesstray'],
    deviceTypeId: 'abe332f9-002d-55bc-9ed9-46262d44e9b7',
    template: {
      name: 'Fahrzeug — Hostess Tray',
      category: RIG,
      subtitle: 'carmount',
      notes: '0.8-1.5 m · travel 50 m · payload 15 kg',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['kamerarickshaw'],
    deviceTypeId: '92b5c1d3-d119-57c1-9d0a-e8ebddb95a01',
    template: {
      name: 'Kamera-Rickshaw',
      category: RIG,
      subtitle: 'rickshaw',
      notes: '0.8-2 m · travel 30 m · payload 60 kg · footprint 0.8x1.6 m',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['steadicamweste'],
    deviceTypeId: '9cedf2e6-04c8-5fbb-bc5d-24d016c524fb',
    template: {
      name: 'Steadicam (Weste)',
      category: RIG,
      subtitle: 'steadicam',
      notes: '0.3-2 m · payload 20 kg',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['gimbaleinhndig'],
    deviceTypeId: 'f41cac6d-9064-5edf-8467-402361c0d4cf',
    template: {
      name: 'Gimbal (einhändig)',
      category: RIG,
      subtitle: 'gimbal',
      notes: '0.3-2.1 m · payload 4.5 kg',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['gimbalheavyronin'],
    deviceTypeId: '0e939ab0-ea0d-522b-9c5c-00a703860522',
    template: {
      name: 'Gimbal (Heavy / Ronin)',
      category: RIG,
      subtitle: 'gimbal',
      notes: '0.3-2.1 m · payload 10 kg',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['schulterhandheld'],
    deviceTypeId: 'fc6b09db-e6bd-50d8-8594-c6894232e11e',
    template: {
      name: 'Schulter / Handheld',
      category: RIG,
      subtitle: 'handheld',
      notes: '1-1.9 m · payload 15 kg',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
  {
    match: ['easyrig'],
    deviceTypeId: '7b1e9251-2c80-5de0-9fab-7457246d5641',
    template: {
      name: 'Easyrig',
      category: RIG,
      subtitle: 'handheld',
      notes: '1-2 m · payload 18 kg · Entlastet die Schulter, lässt die Bewegung ruhiger werden.',
      width: 200,
      height: 120,
      inputs: [],
      outputs: [],
      portsUnknown: true,
    },
  },
]

/** Die Vorlagen allein — fuer die Bibliotheks-Saat in `projectStore`. */
export const rigTemplates: EquipmentTemplate[] =
  RIG_CATALOG.map((e) => ({ ...e.template, deviceTypeId: e.deviceTypeId }))
